spring.datasource.url=jdbc:postgresql://db.pkktouewaqhvnwahoktn.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=BhuvannagesH@1703
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Use a long random secret (min 32 chars)
app.jwt.secret=WealthWise$ecretKey2026!SuperSecureRandomString#MF
app.jwt.expiration-ms=604800000


cors.allowed.origins=http://localhost:5173

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhuvannagesh2004@gmail.com
spring.mail.password=ysxt jxar nuet ioho
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true